wandb:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: nuplan
  group: null
  name: scene_motion_prediction
  notes: "Train scene motion prediction model"
  tags: []
  job_type: train
  entity: kit_mrt
