# @package _global_

defaults:
  - _self_
  - trainer: nuplan
  - model: ac_scene_motion
  - datamodule: h5_nuplan
  - callbacks: wandb
  - loggers: wandb
  - resume: empty

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}

work_dir: ${hydra:runtime.cwd}
seed: 2024
action: fit # fit, validate, test

# Shared parameter for motion planning
use_ego_nav: True
nav_with_route: False
nav_with_goal: False
nav_route_late_fusion: True
nav_goal_late_fusion: False
