_target_: data_modules.data_h5_nuplan.DataH5nuplan

data_dir: "/tmp/steiner/sqfs/mrtstorage/datasets_tmp/nuplan_hptr/nuplan_hptr"
filename_train: training
filename_val: validation
filename_test: testing
n_agent: 64

batch_size: 30
num_workers: 16
